# enable Docker for the repository
options:
docker: true

# Start the pipeline
pipelines:
default:
- step:
script: # Name the image and create a docker image
- docker build -t "registry.jeshkov.ru:5000/jeshkov.ru/puppet/environment_ketchinov/rails46_api:latest" . 
- docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
- docker push registry.jeshkov.ru:5000/jeshkov.ru/puppet/environment_ketchinov/rails46_api:latest
