---
:concurrency: 15
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 30
staging:
  :concurrency: 20
development:
  :concurrency: 15
:queues:
  - critical
  - default
  - mailing
  - mailing_test
  - resize
  - rollbar
  - long
:limits:
  critical: 1
  rollbar: 1
  mailing: 10
  mailing_test: 1
  yml: 2
  long: 5
  default: 5
