---
:concurrency: 15
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 15
staging:
  :concurrency: 111
development:
  :concurrency: 15
:queues:
  - critical
  - default
  - long
  - mailing
  - rollbar
:limits:
  critical: 1
  rollbar: 1
  long: 60
  mailing: 18
  default: 20
