---
:concurrency: 30
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 30
staging:
  :concurrency: 20
development:
  :concurrency: 15
:queues:
  - critical
  - default
  - trigger
  - mailing
  - mailing_test
  - resize
  - rollbar
  - long
  - webpush
  - order
:limits:
  critical: 1
  rollbar: 1
  trigger: 10
  mailing: 10
  mailing_test: 1
  yml: 4
  long: 5
  default: 5
  webpush: 5
  order: 5
