---
:concurrency: 15
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 20
staging:
  :concurrency: 20
development:
  :concurrency: 15
:queues:
  - critical
  - default
  - mailing_test
  - resize
  - rollbar
:limits:
  critical: 1
  rollbar: 1
  mailing: 10
  mailing_test: 1
  long: 2
  default: 5
