---
:concurrency: 15
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 15
development:
  :concurrency: 15
:queues:
  - critical
  - default
  - long
  - mailing
:limits:
  critical: 3
  default: 7
  long:     2
  mailing:  10
