---
:concurrency: 15
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 50
staging:
  :concurrency: 50
development:
  :concurrency: 15
:queues:
  - critical
  - default
  - long
  - mailing
  - resize
  - rollbar
:limits:
  critical: 1
  rollbar: 1
  long: 23
  mailing: 20
  default: 5
